pub use web_sys; // Developers can now use oxirast_core::web_sys!
pub use wasm_bindgen;
use std::cell::RefCell;
use std::rc::Rc;
use wasm_bindgen::prelude::*;
use web_sys::{window, Document, Element, Event};

// ==========================================
// 1. DOM HELPERS
// ==========================================

/// A quick helper to grab the browser's global document object
pub fn document() -> Document {
    window()
        .expect("No global `window` exists")
        .document()
        .expect("Should have a document on window")
}

/// The main entry point for an Oxirast app. 
/// This takes the root element generated by rsx! and attaches it to the <body>.
pub fn mount_to_body(element: &Element) {
    document()
        .body()
        .expect("Document should have a body")
        .append_child(element)
        .expect("Failed to append root element to body");
}

/// A crucial helper function that attaches Rust closures to DOM events.
/// This abstracts away the messy `wasm-bindgen` closure wrapping.
pub fn on_event<F>(element: &Element, event_name: &str, mut callback: F)
where
    // The callback must take an Event and return nothing
    F: FnMut(Event) + 'static, 
{
    // Wrap the Rust closure so JavaScript can understand it
    let closure = Closure::wrap(Box::new(move |e: Event| {
        callback(e);
    }) as Box<dyn FnMut(_)>);

    // Attach it to the HTML element
    element
        .add_event_listener_with_callback(event_name, closure.as_ref().unchecked_ref())
        .expect("Failed to add event listener");

    // In a production framework, we would carefully track this to prevent memory leaks.
    // For our prototype, we tell Rust to "forget" it so the listener stays alive forever.
    closure.forget();
}

// ==========================================
// 2. THE REACTIVITY ENGINE (Signals)
// ==========================================

#[derive(Clone)]
pub struct Signal<T> {
    value: Rc<RefCell<T>>,
    listeners: Rc<RefCell<Vec<Box<dyn FnMut(&T)>>>>,
}

impl<T: Clone + 'static> Signal<T> {
    pub fn new(initial_value: T) -> Self {
        Self {
            value: Rc::new(RefCell::new(initial_value)),
            listeners: Rc::new(RefCell::new(Vec::new())),
        }
    }

    pub fn get(&self) -> T {
        self.value.borrow().clone()
    }

    pub fn set(&self, new_value: T) {
        *self.value.borrow_mut() = new_value.clone();
        let mut listeners = self.listeners.borrow_mut();
        for listener in listeners.iter_mut() {
            listener(&new_value);
        }
    }

    pub fn subscribe<F>(&self, callback: F)
    where
        F: FnMut(&T) + 'static,
    {
        self.listeners.borrow_mut().push(Box::new(callback));
    }
}

pub fn use_state<T: Clone + 'static>(initial: T) -> Signal<T> {
    Signal::new(initial)
}