[package]
name = "oxirast-cli"
description = "A fast, fine-grained WebAssembly frontend framework for Rust."
license = "MIT"
repository = "https://github.com/Michaelmk708/oxirast-rust_web_framework"
version = "1.0.1"
edition = "2021"
authors = ["Michael Kinuthia <michaelkinuthia708@gmail.com>"]
readme = "../README.md" 
keywords = ["wasm", "frontend", "webassembly", "framework", "reactivity"]
categories = ["wasm", "web-programming"]

[dependencies]
tokio = { version = "1.36", features = ["full"] }
axum = { version = "0.7", features = ["ws"] }
notify = "6.1"
futures = "0.3"
tower-http = { version = "0.5", features = ["fs"] }